### ISSUE TITLE
视觉效果对比图

### ISSUE THREAD

**Issue by duweihua** [Shaosifan/TransENet#11]
![image](https://user-images.githubusercontent.com/43801202/236991484-d4891e85-49ce-42f4-8cd8-56c991ebdb95.png)
你好，文章中的视觉效果对比图是需要retrain这些模型的吗 ？能否提供这些方法在AID和UCMerced数据集上复原的图像？ 谢谢

**Comment by rtrtfs** [comment]
我也想要这些方法在AID和UCMerced数据集上复原的图像，还有这些裁剪的区域的位置可以说一下吗

**Comment by rtrtfs** [comment]
我也是想知道这个问题
&nbsp;


帅男孩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月9日(星期二) 下午5:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [Shaosifan/TransENet] 视觉效果对比图 (Issue #11)





 

 你好，文章中的视觉效果对比图是需要retrain这些模型的吗 ？能否提供这些方法在AID和UCMerced数据集上复原的图像？ 谢谢

**Comment by Shaosifan** [comment]
这些算法都是retrain过的。论文中贴的相关视觉对比图，可从这个链接上下载：[[Baidu Drive](https://pan.baidu.com/s/1LT6mg3BAu1VXhx251qIFQw), password: sm3g]

**Comment by duweihua** [comment]
> 这些算法都是retrain过的。论文中贴的相关视觉对比图，可从这个链接上下载：[[Baidu Drive](https://pan.baidu.com/s/1LT6mg3BAu1VXhx251qIFQw), password: sm3g]

这个只有论文中的贴图，没有retrained 算法复原的所有图像吗？

**Comment by Shaosifan** [comment]
我这边目前找到的有AID数据集上各个方法复原的所有图像：[[Baidu Drive](https://pan.baidu.com/s/1-uKdxyKX1ozqfB6ZIB-G2Q ), password: 0tul]

**Comment by duweihua** [comment]
嗯嗯好的，非常感谢。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月14日 22:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Shaosifan/TransENet] 视觉效果对比图 (Issue #11) |

我这边目前找到的有AID数据集上各个方法复原的所有图像：[Baidu Drive, password: 0tul]
