### ISSUE TITLE
视觉效果对比图的裁剪区域大小

### ISSUE THREAD

**Issue by rtrtfs** [Shaosifan/TransENet#12]
![M D5YZM_3L3HYO@R@_ 1(JT](https://github.com/Shaosifan/TransENet/assets/96280192/a294a0b4-015c-45ed-b092-63a9459fb9b4)
我想问一下可以提供一下这个裁剪的大小，还有坐标在哪里，然后就是通过什么方法裁剪的，非常感谢作者。

**Comment by Shaosifan** [comment]
您好，之前我做实验，采用Photoshop(PS)进行的截图，将相同场景的实验结果图片导入到PS中，然后不同方法的重建图片对应不同的图层，使用PS中的裁剪工具，可以一次性地截取到所有图片的相同区域，然后再分别对每个图层的结果进行无损存储，这样不会对重建结果有影响并能保证是同一位置。但这种方式不能获取截图的准确位置。

或者您可以在PS中查看裁剪区域的大小和坐标（PS中可以看到相关信息），然后使用脚本截取，这样也是可以的。

**Comment by rtrtfs** [comment]
非常感谢！&nbsp;


帅男孩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月18日(星期四) 中午11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Shaosifan/TransENet] 视觉效果对比图的裁剪区域大小 (Issue #12)





 
您好，之前我做实验，采用Photoshop(PS)进行的截图，将相同场景的实验结果图片导入到PS中，然后不同方法的重建图片对应不同的图层，使用PS中的裁剪工具，可以一次性地截取到所有图片的相同区域，然后再分别对每个图层的结果进行无损存储，这样不会对重建结果有影响并能保证是同一位置。但这种方式不能获取截图的准确位置。
 
或者您可以在PS中查看裁剪区域的大小和坐标（PS中可以看到相关信息），然后使用脚本截取，这样也是可以的。
