### ISSUE TITLE
About Pretrained models

### ISSUE THREAD

**Issue by Rheazheng** [Shaosifan/TransENet#13]
Hi,Could you support the pretrained models about TransENet?Thanks.
I try to retrain the model,but there are some questions. The test  results are so bad.

**Comment by Shaosifan** [comment]
Hi, we have released the pre-trained TransENet models on UCMerced and AID datasets which can be found here [[Baidu Drive](https://pan.baidu.com/s/1lvAyTagbBf5GWUOcuEkyrQ), password:w7ct][[Google Drive](https://drive.google.com/file/d/19nH1Plh2M-Z47iXG0-Ghq-Orh33n787w/view)].
