### ISSUE TITLE
Ucmerd数据集

### ISSUE THREAD

**Issue by rtrtfs** [Shaosifan/TransENet#14]
你好，我想问一下，论文里的数据集是按照您百度网盘提供的数据集进行训练的吗，您百度网盘提供的ucmerd数据集，验证集有105张，是按照10%的训练集划分的，不过今天才看到论文里面写的是20%的训练集作为验证集。所以想问一下。

**Comment by Shaosifan** [comment]
> 你好，我想问一下，论文里的数据集是按照您百度网盘提供的数据集进行训练的吗，您百度网盘提供的ucmerd数据集，验证集有105张，是按照10%的训练集划分的，不过今天才看到论文里面写的是20%的训练集作为验证集。所以想问一下。

是使用百度网盘中的数据集进行训练的。在论文中写的，是将整个数据集一半分为训练集，一半为测试集，其中训练集的20%为验证集，这样验证集的数目其实占整个数据集的话，就是10%了。

**Comment by rtrtfs** [comment]
> > 你好，我想问一下，论文里的数据集是按照您百度网盘提供的数据集进行训练的吗，您百度网盘提供的ucmerd数据集，验证集有105张，是按照10%的训练集划分的，不过今天才看到论文里面写的是20%的训练集作为验证集。所以想问一下。
> 
> 是使用百度网盘中的数据集进行训练的。在论文中写的，是将整个数据集一半分为训练集，一半为测试集，其中训练集的20%为验证集，这样验证集的数目其实占整个数据集的话，就是10%了。

谢谢您的回答，不过网盘提供的验证集是训练集的百分10，只有105张，占训练集的20%，不应该是210张图片吗

**Comment by Shaosifan** [comment]
> > > 你好，我想问一下，论文里的数据集是按照您百度网盘提供的数据集进行训练的吗，您百度网盘提供的ucmerd数据集，验证集有105张，是按照10%的训练集划分的，不过今天才看到论文里面写的是20%的训练集作为验证集。所以想问一下。
> > 
> > 
> > 是使用百度网盘中的数据集进行训练的。在论文中写的，是将整个数据集一半分为训练集，一半为测试集，其中训练集的20%为验证集，这样验证集的数目其实占整个数据集的话，就是10%了。
> 
> 谢谢您的回答，不过网盘提供的验证集是训练集的百分10，只有105张，占训练集的20%，不应该是210张图片吗

我检查了一下，应该是论文中这里出现了笔误。模型训练是使用百度网盘中的数据，train set 共为945张图片，val set共有105张图片，test set共有1050张图片。因此，论文中的描述，应该是10%的训练集作为验证集，感谢您指出这个问题。

**Comment by rtrtfs** [comment]
> 

好的，谢谢您
