### ISSUE TITLE
why are there checkerboard artifacts in the SR image?

### ISSUE THREAD

**Issue by JQJ001** [Shaosifan/TransENet#15]
Thank you for sharing the code.

When I load the trained TransENet model on UCMerced-4x to test, there are lots of checkerboard artifacts in the SR image, as shown below:
![QQ图片20240408205153](https://github.com/Shaosifan/TransENet/assets/31473581/9b210d68-b8c3-484b-96b6-51013e1310c7)

Can you tell me the possible cause of artifacts?
Looking forward to your reply.

**Comment by Shaosifan** [comment]
> Thank you for sharing the code.
> 
> When I load the trained TransENet model on UCMerced-4x to test, there are lots of checkerboard artifacts in the SR image, as shown below: ![QQ图片20240408205153](https://private-user-images.githubusercontent.com/31473581/320488365-9b210d68-b8c3-484b-96b6-51013e1310c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTcyNDksIm5iZiI6MTcxMjg5Njk0OSwicGF0aCI6Ii8zMTQ3MzU4MS8zMjA0ODgzNjUtOWIyMTBkNjgtYjhjMy00ODRiLTk2YjYtNTEwMTNlMTMxMGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA0NDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNjY2MjE2ZjkzMDIzYzliMTYwNWE0ZDg5ODk4MzE2YWQ5ZjY1OTAxMTUzYWMzZjYyYmM1MTQ4OTQyNDFjM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a6-bAAbCCFdxZrZ2TpcYhZysDfae8PZHOvhEUjORBL4)
> 
> Can you tell me the possible cause of artifacts? Looking forward to your reply.

Hi, thank you for pointing out this mistake. 

I check the model and also find this problem. Therefore, I update the model for UCMerced-4x, and the super-resolved image is shown as below:
![image](https://github.com/Shaosifan/TransENet/assets/11569901/e433bbbe-6a0b-4eb0-807a-08846850af77)
