### ISSUE TITLE
关于分类后的数据集

### ISSUE THREAD

**Issue by tarxs** [Shaosifan/TransENet#16]
作者你好，
        请问能分享一下UCMerced和AID数据集分成每种类别的LR和HR图像数据集吗

**Comment by Shaosifan** [comment]
您好，数据可以在项目主页上下载，所有类别的LR和HR的数据都放在了一个目录下，您可以通过文件名，将对应类别的数据进行整理。

**Comment by tarxs** [comment]
> 您好，数据可以在项目主页上下载，所有类别的LR和HR的数据都放在了一个目录下，您可以通过文件名，将对应类别的数据进行整理。

感谢你提供整体的数据集，我已经使用了。就是想问问你是否保存了分类后的数据集，可供分享。

**Comment by Shaosifan** [comment]
> > 您好，数据可以在项目主页上下载，所有类别的LR和HR的数据都放在了一个目录下，您可以通过文件名，将对应类别的数据进行整理。
> 
> 感谢你提供整体的数据集，我已经使用了。就是想问问你是否保存了分类后的数据集，可供分享。

分类后数据集是指？

**Comment by tarxs** [comment]
> 分类后数据集是指？
![%DFKXP_KS4BBBVUK2{6ZHKD](https://github.com/Shaosifan/TransENet/assets/45535068/dc7237a0-a23c-457e-a790-53ffb79c0744)
就是类似于这样的文件夹，每个类别一个文件夹，里面有HR和LR的文件夹

**Comment by Shaosifan** [comment]
> > 分类后数据集是指？
> > ![%DFKXP_KS4BBBVUK2{6ZHKD](https://private-user-images.githubusercontent.com/45535068/323625560-dc7237a0-a23c-457e-a790-53ffb79c0744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTEyMTYsIm5iZiI6MTcxMzQ1MDkxNiwicGF0aCI6Ii80NTUzNTA2OC8zMjM2MjU1NjAtZGM3MjM3YTAtYTIzYy00NTdlLWE3OTAtNTNmZmI3OWMwNzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE0MzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhODNhNDg1OTIwY2MzMTg5M2EzZWVlMzYyMjBlZDc0MjNmNDlmOGI3ZTU0MzRmOWM5YTU5MGNlZjM3ZTc2MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uV_wkcTp9p5eL4ux4aKfQdpcPiVvTDu2lwmn6n3lgXU)
> > 就是类似于这样的文件夹，每个类别一个文件夹，里面有HR和LR的文件夹

不好意思，我没有构建这样的文件夹，我是统一放在了一块的
