### ISSUE TITLE
测试图片出现严重伪影现象

### ISSUE THREAD

**Issue by poosoo** [Shaosifan/TransENet#18]
我用TransENet-ucmerced-x4.pt测试的UC Merced，图片是这样怎么回事呢
![intersection06](https://github.com/user-attachments/assets/a8fd386c-d641-4e37-a33c-ed996d94d0ee)

**Comment by CCisCalm** [comment]
你好，请问你解决了吗？我从Google Drive里面下载的预训练权重进行测试，同样出现了这个问题。

**Comment by Shaosifan** [comment]
> 你好，请问你解决了吗？我从Google Drive里面下载的预训练权重进行测试，同样出现了这个问题。

使用一下百度网盘下载的预训练权重试一下呢

**Comment by CCisCalm** [comment]
你好，我百度网盘下载的权重试了，解决了上面的问题，但是测试后结果的PSNR和SSIM指标有些许出入，不知道是不是我参数设置有问题或者是因为系统驱动/环境不同的原因（我按照开源的test指令进行测试的，--model=TRANSENET --scale=4，patch_size应该是192 for x4）。目前有篇类似的工作在进行对比试验，感谢作者的解答。

**Comment by CCisCalm** [comment]
你好，我百度网盘下载的权重试了，解决了上面的问题，但是测试后结果的PSNR和SSIM指标有些许出入，不知道是不是我参数设置有问题或者是因为系统驱动/环境不同的原因（我按照开源的test指令进行测试的，--model=TRANSENET --scale=4，patch_size默认是192 for x4）。
我也在另一篇HSENet进行了测试，同样预训练权重的测试结果指标存在些许出入，我感觉应该是我某处细节没有注意到的原因。
目前有篇类似的工作在进行对比试验，期待作者的解答，感谢！

**Comment by Shaosifan** [comment]
> 你好，我百度网盘下载的权重试了，解决了上面的问题，但是测试后结果的PSNR和SSIM指标有些许出入，不知道是不是我参数设置有问题或者是因为系统驱动/环境不同的原因（我按照开源的test指令进行测试的，--model=TRANSENET --scale=4，patch_size默认是192 for x4）。 我也在另一篇HSENet进行了测试，同样预训练权重的测试结果指标存在些许出入，我感觉应该是我某处细节没有注意到的原因。 目前有篇类似的工作在进行对比试验，期待作者的解答，感谢！

差异有多大呢？

**Comment by CCisCalm** [comment]
> > 你好，我百度网盘下载的权重试了，解决了上面的问题，但是测试后结果的PSNR和SSIM指标有些许出入，不知道是不是我参数设置有问题或者是因为系统驱动/环境不同的原因（我按照开源的test指令进行测试的，--model=TRANSENET --scale=4，patch_size默认是192 for x4）。 我也在另一篇HSENet进行了测试，同样预训练权重的测试结果指标存在些许出入，我感觉应该是我某处细节没有注意到的原因。 目前有篇类似的工作在进行对比试验，期待作者的解答，感谢！
> 
> 差异有多大呢？

Average: PSNR: 27.601771 dB, SSIM: 0.756061，UCMerced x4测试出来是这个结果。

**Comment by CCisCalm** [comment]
> > > 你好，我百度网盘下载的权重试了，解决了上面的问题，但是测试后结果的PSNR和SSIM指标有些许出入，不知道是不是我参数设置有问题或者是因为系统驱动/环境不同的原因（我按照开源的test指令进行测试的，--model=TRANSENET --scale=4，patch_size默认是192 for x4）。 我也在另一篇HSENet进行了测试，同样预训练权重的测试结果指标存在些许出入，我感觉应该是我某处细节没有注意到的原因。 目前有篇类似的工作在进行对比试验，期待作者的解答，感谢！
> > 
> > 
> > 差异有多大呢？
> 
> Average: PSNR: 27.601771 dB, SSIM: 0.756061，UCMerced x4测试出来是这个结果。

哥，如果方便的话，可以加个wx吗？ccww20616

**Comment by Shaosifan** [comment]
> > > 你好，我百度网盘下载的权重试了，解决了上面的问题，但是测试后结果的PSNR和SSIM指标有些许出入，不知道是不是我参数设置有问题或者是因为系统驱动/环境不同的原因（我按照开源的test指令进行测试的，--model=TRANSENET --scale=4，patch_size默认是192 for x4）。 我也在另一篇HSENet进行了测试，同样预训练权重的测试结果指标存在些许出入，我感觉应该是我某处细节没有注意到的原因。 目前有篇类似的工作在进行对比试验，期待作者的解答，感谢！
> > 
> > 
> > 差异有多大呢？
> 
> Average: PSNR: 27.601771 dB, SSIM: 0.756061，UCMerced x4测试出来是这个结果。

不同的环境可能有一定的出入，建议可以在你本地环境中重新训一遍。

**Comment by CCisCalm** [comment]
> > > > 你好，我百度网盘下载的权重试了，解决了上面的问题，但是测试后结果的PSNR和SSIM指标有些许出入，不知道是不是我参数设置有问题或者是因为系统驱动/环境不同的原因（我按照开源的test指令进行测试的，--model=TRANSENET --scale=4，patch_size默认是192 for x4）。 我也在另一篇HSENet进行了测试，同样预训练权重的测试结果指标存在些许出入，我感觉应该是我某处细节没有注意到的原因。 目前有篇类似的工作在进行对比试验，期待作者的解答，感谢！
> > > 
> > > 
> > > 差异有多大呢？
> > 
> > 
> > Average: PSNR: 27.601771 dB, SSIM: 0.756061，UCMerced x4测试出来是这个结果。
> 
> 不同的环境可能有一定的出入，建议可以在你本地环境中重新训一遍。

好嘞，感谢，我重新训练试一试
