### ISSUE TITLE
代码中缺少需要的函数

### ISSUE THREAD

**Issue by zsz-pro** [Shaosifan/TransENet#2]
![image](https://user-images.githubusercontent.com/61933660/156488662-40ef8a6b-aec3-4f6d-9902-fc8e82126051.png)
在generate_mod_LR_bic文件中用到imresize_np并没有提供。可以麻烦补充下吗，谢谢

**Comment by Shaosifan** [comment]
感谢您的提问，已经上传到这里了
https://github.com/Shaosifan/TransENet/blob/master/codes/data/util.py
