### ISSUE TITLE
loss

### ISSUE THREAD

**Issue by muzili5** [Shaosifan/TransENet#4]
Excuse me, I can't find loss.pt after running demo_train, where did this loss weight come from?

**Comment by Shaosifan** [comment]
The loss.pt file is in the save folder of the experiment dir.

**Comment by muzili5** [comment]
> experimen

But there is no loss.pt in my experiment dir. How is loss.pt generated and saved in the experiment directory?

**Comment by Shaosifan** [comment]
When you use this code to train on a scale factor of x4, the save folder 'TRANSENETx4_UCMerced' will be generated in the experiment directory:

`python demo_train.py --model=TRANSENET --dataset=UCMerced --scale=4 --patch_size=192 --ext=img --save=TRANSENETx4_UCMerced `

And the loss.pt will be saved in the 'TRANSENETx4_UCMerced' folder during training. The save code is at [trainer.loss.save(self.dir)](https://github.com/Shaosifan/TransENet/blob/1ebc2e43961e8590f166ee7bb2b4c7f98e4d34b3/codes/utils.py#L101)

This is the content in my generated folder here:
![test](https://user-images.githubusercontent.com/11569901/186623726-4df82b0d-366f-47cc-9217-2ff14a6842db.png)

**Comment by muzili5** [comment]
But when I run it as you did, it shows ImportError: DLL load failed while importing ft2font: 找不到指定的模块。Are there any other directories in the code that need to be modified?

**Comment by muzili5** [comment]
Please tell me how to solve the error einops.EinopsError:  Error while processing rearrange-reduction pattern "b (h w) (p1 p2 c) -> b c (h p1) (w p2)".
 Input tensor shape: torch.Size([16, 1024, 1024]). Additional info: {'h': 24, 'p1': 8, 'p2': 8}.
 Shape mismatch, can't divide axis of length 1024 in chunks of 24 after running halfway

**Comment by Shaosifan** [comment]
> Please tell me how to solve the error einops.EinopsError: Error while processing rearrange-reduction pattern "b (h w) (p1 p2 c) -> b c (h p1) (w p2)". Input tensor shape: torch.Size([16, 1024, 1024]). Additional info: {'h': 24, 'p1': 8, 'p2': 8}. Shape mismatch, can't divide axis of length 1024 in chunks of 24 after running halfway

It is suggested to check the shape of input when using rearrange function.
