### ISSUE TITLE
Dataset used in the paper

### ISSUE THREAD

**Issue by DaxingZ** [Shaosifan/TransENet#5]
Thanks for your great job introducing Transformer into remote sensing image SR!
About the dataset used in the paper, could you provide it directly?  Is the UCMereced dataset  split into two parts randomly?

**Comment by Shaosifan** [comment]
The dataset links:
UCMerced dataset[[Baidu Drive](https://pan.baidu.com/s/1bxHHqKpVSyj5CiW4S6ZzDQ),password:0oaj][[Google Drive](https://drive.google.com/file/d/1eKvoe6W7q5qD33MaqujzCAPtwNZqVsKB/view)]and AID dataset[[Baidu Drive](https://pan.baidu.com/s/1Cf-J_YdcCB2avPEUZNBoCA),password:id1n][[Google Drive](https://drive.google.com/file/d/1d_Wq_U8DW-dOC3etvF4bbbWMOEqtZwF7/view)]
