### ISSUE TITLE
关于LR/HR影像对

### ISSUE THREAD

**Issue by Eliaukyxw** [Shaosifan/TransENet#6]
您好！读了您的论文之后我非常想尝试一下TransENet模型来适用于我现阶段的实验。
  目前我已经收集了LR/HR影像对，但这些遥感影像尺寸较大为tif文件并且有24个波段，请问应该如何制作patches并且适用于您这里的网络呢？
  期待您的回复！非常感谢！

**Comment by Shaosifan** [comment]
感谢您对我们工作的关注。
目前TransENet仅支持RGB数据，针对你的实验情况，如果tif图像的尺寸非常大，需要先裁剪生成若干的tif小图，同时需要改写srdata.py中数据读取部分从而能够解析24个波段的tif文件（cv2应该不支持此种类型格式的读取），对于TransENet模型，将对应的通道数改成24。希望能够对您的工作有所帮助。

**Comment by Eliaukyxw** [comment]
感谢您的及时回复！我将尝试您提到的建议，后续会做出反馈。
