### ISSUE TITLE
关于train AID数据集的rgb_mean和rgb_std 

### ISSUE THREAD

**Issue by 237014845** [Shaosifan/TransENet#9]
您好，AID数据集的rgb_mean和rgb_std ，您有计算吗？我在代码里只看到rgb_mean = (0.4916, 0.4991, 0.4565)  # UCMerced data
        rgb_std = (1.0, 1.0, 1.0)

**Comment by Shaosifan** [comment]
您好，我这边计算的AID数据集的rgb_mean=(0.3973, 0.4088, 0.3683), rgb_std=(1.0, 1.0, 1.0) ，其中主要是通过计算AID中训练集中HR像素值得到，rgb_std的取值参考自然图像中的设置。

不过我在实验中，并没有仔细测试不同的rgb_mean取值对最终重建结果有多大的影响，如果您做了相关实验，有什么有趣的现象，也欢迎您在此处分享，谢谢！

**Comment by 237014845** [comment]
非常感谢您的回复！这些数据对我的实验很有帮助！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ls ***@***.***&gt;
发送时间: 2023年5月18日 11:46
收件人: Shaosifan/TransENet ***@***.***&gt;
抄送: DLUT_HS ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Shaosifan/TransENet] 关于train AID数据集的rgb_mean和rgb_std  (Issue #9)





 
您好，我这边计算的AID数据集的rgb_mean=(0.3973, 0.4088, 0.3683), rgb_std=(1.0, 1.0, 1.0) ，其中主要是通过计算AID中训练集中HR像素值得到，rgb_std的取值参考自然图像中的设置。
 
不过我在实验中，并没有仔细测试不同的rgb_mean取值对最终重建结果有多大的影响，如果您做了相关实验，有什么有趣的现象，也欢迎您在此处分享，谢谢！
